modLoader="javafml"

loaderVersion="[43,)"

license="MIT"

[[mods]]

modId="tfmg"

version="0.7.0c"

displayName="Create: The Factory Must Grow"

logoFile="logo.png"

authors="DrMangoTea, Pepa, Milky, Luna"

description='''
description soon
'''

[[dependencies.tfmg]]

    modId="forge"

    mandatory=true

    versionRange="[43,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.tfmg]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
