modLoader="javafml"

loaderVersion="[43,)"

license="MIT"

[[mods]]

modId="tfmg"

version="${file.jarVersion}"

displayName="Create: The Factory Must Grow"

logoFile="logo.png"

authors="DrMangoTea, Pepa, Milky"

description='''
description soon
'''

[[dependencies.tfmg]]

    modId="forge"

    mandatory=true

    versionRange="[43,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.tfmg]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
